/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TeamStoresRouteImport } from './routes/team-stores'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as UniformsRouteImport } from './routes/uniforms'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as SportsSportRouteImport } from './routes/sports.$sport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamStoresRoute = TeamStoresRouteImport.update({
  id: '/team-stores',
  path: '/team-stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformsRoute = UniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportRoute = SportsSportRouteImport.update({
  id: '/sports/$sport',
  path: '/sports/$sport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/team-stores': typeof TeamStoresRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/uniforms': typeof UniformsRoute
  '/sports/$sport': typeof SportsSportRoute
  '/sports/': typeof SportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/team-stores': typeof TeamStoresRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/uniforms': typeof UniformsRoute
  '/sports/$sport': typeof SportsSportRoute
  '/sports': typeof SportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/team-stores': typeof TeamStoresRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/uniforms': typeof UniformsRoute
  '/sports/$sport': typeof SportsSportRoute
  '/sports/': typeof SportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/how-it-works'
    | '/privacy'
    | '/quote'
    | '/resources'
    | '/solutions'
    | '/team-stores'
    | '/terms'
    | '/track-order'
    | '/uniforms'
    | '/sports/$sport'
    | '/sports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/how-it-works'
    | '/privacy'
    | '/quote'
    | '/resources'
    | '/solutions'
    | '/team-stores'
    | '/terms'
    | '/track-order'
    | '/uniforms'
    | '/sports/$sport'
    | '/sports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/how-it-works'
    | '/privacy'
    | '/quote'
    | '/resources'
    | '/solutions'
    | '/team-stores'
    | '/terms'
    | '/track-order'
    | '/uniforms'
    | '/sports/$sport'
    | '/sports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRoute
  TeamStoresRoute: typeof TeamStoresRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  UniformsRoute: typeof UniformsRoute
  SportsSportRoute: typeof SportsSportRoute
  SportsIndexRoute: typeof SportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-stores': {
      id: '/team-stores'
      path: '/team-stores'
      fullPath: '/team-stores'
      preLoaderRoute: typeof TeamStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniforms': {
      id: '/uniforms'
      path: '/uniforms'
      fullPath: '/uniforms'
      preLoaderRoute: typeof UniformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sport': {
      id: '/sports/$sport'
      path: '/sports/$sport'
      fullPath: '/sports/$sport'
      preLoaderRoute: typeof SportsSportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRoute,
  TeamStoresRoute: TeamStoresRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  UniformsRoute: UniformsRoute,
  SportsSportRoute: SportsSportRoute,
  SportsIndexRoute: SportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
